# Generated by Django 4.1.5 on 2023-02-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=450, null=True, verbose_name='Shop Name')),
                ('address', models.CharField(blank=True, max_length=1000, verbose_name='Shop Address')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
