# Generated by Django 4.1.5 on 2023-01-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='child_field',
            new_name='parent',
        ),
    ]
