# Generated by Django 4.1.5 on 2023-02-10 12:16

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_reviews_unique_together'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Product Name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='NewGinIndex'),
        ),
    ]
