# Generated by Django 4.1.5 on 2023-02-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_product_name_product_newginindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Product Store Number'),
        ),
    ]
