# Generated by Django 4.1.5 on 2023-01-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_product_showed_price_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sold_stock',
            field=models.IntegerField(default=0),
        ),
    ]
