# Generated by Django 4.1.5 on 2023-03-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='in_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sold_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_stock',
            field=models.IntegerField(default=1),
        ),
    ]
