# Generated by Django 4.1.5 on 2023-01-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_alter_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.TextField(blank=True, max_length=72, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.product'),
        ),
    ]
