# Generated by Django 4.1.5 on 2023-01-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_excerpt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Product Short Description'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='commerce.product'),
        ),
    ]
