# Generated by Django 4.1.5 on 2023-01-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_product_product_excerpt_alter_reviews_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
