# Generated by Django 4.1.5 on 2023-02-02 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0012_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='saved_post',
        ),
        migrations.AddField(
            model_name='product',
            name='saved_post',
            field=models.ManyToManyField(null=True, related_name='user_saved_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
