# Generated by Django 4.1.5 on 2023-02-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_seller_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('-name',)},
        ),
    ]
