# Generated by Django 4.1.5 on 2023-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_state_alter_addressglobal_state_delete_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=72),
        ),
    ]
