# Generated by Django 4.1.5 on 2023-02-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_addressglobal_price_alter_addressglobal_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressglobal',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
