# Generated by Django 4.1.5 on 2023-02-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_addressglobal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressglobal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
