# Generated by Django 4.1.5 on 2023-03-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_dummymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
