# Generated by Django 4.1.5 on 2023-03-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_dummymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressglobal',
            name='price',
        ),
    ]
