# Generated by Django 4.1.5 on 2023-03-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_addressglobal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressglobal',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
